'use client'

/**
 * Add Quarterly Sheet Modal
 *
 * Modal for registering a new quarterly sheet
 */

import { useState } from 'react'
import { Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { useToast } from '@/hooks/use-toast'

interface AddQuarterlySheetModalProps {
  onSheetAdded: () => void
}

export function AddQuarterlySheetModal({ onSheetAdded }: AddQuarterlySheetModalProps) {
  const { toast } = useToast()
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)

  const [year, setYear] = useState<string>('')
  const [quarter, setQuarter] = useState<string>('')
  const [group, setGroup] = useState<string>('')
  const [sheetUrl, setSheetUrl] = useState<string>('')
  const [sheetName, setSheetName] = useState<string>('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!year || !quarter || !group || !sheetUrl || !sheetName) {
      toast({
        title: 'Validation Error',
        description: 'Please fill in all required fields (Year, Quarter, Group, Sheet URL, Sheet Name)',
        variant: 'destructive',
      })
      return
    }

    setLoading(true)

    try {
      const response = await fetch('/api/pipelines/quarterly-sheets', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          year: parseInt(year),
          quarter: parseInt(quarter),
          group,
          sheet_url: sheetUrl,
          sheet_name: sheetName,
        }),
      })

      const data = await response.json()

      if (data.success) {
        toast({
          title: '✅ Sheet Added',
          description: data.message,
        })

        // Reset form
        setYear('')
        setQuarter('')
        setGroup('')
        setSheetUrl('')
        setSheetName('')

        setOpen(false)
        onSheetAdded()
      } else {
        toast({
          title: 'Error',
          description: data.error || 'Failed to add sheet',
          variant: 'destructive',
        })
      }
    } catch (error: any) {
      console.error('Failed to add sheet:', error)
      toast({
        title: 'Error',
        description: error.message || 'Network error',
        variant: 'destructive',
      })
    } finally {
      setLoading(false)
    }
  }

  // Auto-generate sheet name preview
  const autoGeneratedName = group && quarter && year
    ? `SEA_${group.toUpperCase()}_Q${quarter}_${year}`
    : ''

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="mr-2 h-4 w-4" />
          Add Quarterly Sheet
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Add Quarterly Sheet</DialogTitle>
          <DialogDescription>
            Register a new Google Sheet for quarterly pipeline sync
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            {/* Year */}
            <div className="grid gap-2">
              <Label htmlFor="year">Year *</Label>
              <Select value={year} onValueChange={setYear} required>
                <SelectTrigger>
                  <SelectValue placeholder="Select year" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem key="year-2024" value="2024">2024</SelectItem>
                  <SelectItem key="year-2025" value="2025">2025</SelectItem>
                  <SelectItem key="year-2026" value="2026">2026</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Quarter */}
            <div className="grid gap-2">
              <Label htmlFor="quarter">Quarter *</Label>
              <Select value={quarter} onValueChange={setQuarter} required>
                <SelectTrigger>
                  <SelectValue placeholder="Select quarter" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem key="quarter-1" value="1">Q1</SelectItem>
                  <SelectItem key="quarter-2" value="2">Q2</SelectItem>
                  <SelectItem key="quarter-3" value="3">Q3</SelectItem>
                  <SelectItem key="quarter-4" value="4">Q4</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Group */}
            <div className="grid gap-2">
              <Label htmlFor="group">Group *</Label>
              <Select value={group} onValueChange={setGroup} required>
                <SelectTrigger>
                  <SelectValue placeholder="Select group" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem key="group-sales" value="sales">Sales</SelectItem>
                  <SelectItem key="group-cs" value="cs">CS</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Sheet URL */}
            <div className="grid gap-2">
              <Label htmlFor="sheetUrl">Google Sheet URL *</Label>
              <Input
                id="sheetUrl"
                type="url"
                placeholder="https://docs.google.com/spreadsheets/d/..."
                value={sheetUrl}
                onChange={(e) => setSheetUrl(e.target.value)}
                required
              />
            </div>

            {/* Sheet Name */}
            <div className="grid gap-2">
              <Label htmlFor="sheetName">Sheet Name *</Label>
              <Input
                id="sheetName"
                type="text"
                placeholder="Must match exactly in Google Sheets"
                value={sheetName}
                onChange={(e) => setSheetName(e.target.value)}
                required
              />
              <p className="text-xs text-muted-foreground">
                ⚠️ Must match the sheet tab name in Google Sheets exactly
              </p>
              <p className="text-xs text-muted-foreground">
                Suggestion: Check your Google Sheet tab name (at the bottom)
              </p>
            </div>
          </div>

          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={loading}>
              {loading ? 'Adding...' : 'Add Sheet'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
